plugin_blacklist:
# common
- safety_area
# extras
- image_pub
- vibration
- distance_sensor
- cam_imu_sync
- local_position
- global_position
- px4flow
- ftp
- mocap_pose_estimate
- setpoint_accel
- setpoint_position
- setpoint_velocity
- waypoint
- vision_pose_estimate
- vision_speed_estimate
- vfr_hud

plugin_whitelist: []
#- 'sys_*'
