rate:
  simulation: 1000.0
  odom: 100.0
noise:
  imu:
    accel:
      init_bias: 
        x: -0.1
        y: 0.0
        z: 0.0
      stddev:
        x: 0.02
        y: 0.0
        z: 0.0
      walk_stddev:
        x: 0.0
        y: 0.0
        z: 0.0
    gyro:
      init_bias: 
        x: 0.1
        y: 0.0
        z: 0.0
      stddev:
        x: 0.02
        y: 0.0
        z: 0.0
      walk_stddev:
        x: 0.0
        y: 0.0
        z: 0.0
